spring:
  application:
    name: mini_project_development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: "jdbc:mysql://localhost:3308/mini_project"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  security:
    user:
      name: admin
      password: admin